function [fitresult, gof] = createFit_tf(t, q)
%CREATEFIT(T,Q)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t
%      Y Output: q
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Dec-2020 03:59:13


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t, q );

% Set up fittype and options.
ft = fittype( 'transferFit(x,k,w,z)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 400 0];
opts.StartPoint = [1 500 1];
opts.Upper = [5 600 5];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );


