%% Final figures - plots only, using saved & loaded data from
% Heat2_Apr19_finalAnalysis.m for heating data (2nd run)

% Instructions: 
% Load saved data
% Create named figure --> can refer to its axes etc.
% Plot data
% Insert figure properties block
% Modify as needed

%% Cody's formatting block + color black

% figure;
% hold on
% set(gca,...
%         'FontUnits','points',...
%         'FontWeight','normal',...
%         'FontSize',16,...
%         'FontName','Helvetica',...
%         'LineWidth',1.25,...
%         'Box','on',...
%         'XGrid','on',...
%         'YGrid','on',...
%         'XColor','k',...
%         'YColor','k')
% ylabel({'Y Axis Label [units]'},...
%         'FontUnits','points',...
%         'FontSize',20,...
%         'FontName','Helvetica')
% xlabel({'X Axis Label [units]'},...
%         'FontUnits','points',...
%         'FontSize',20,...
%         'FontName','Helvetica')

%% Load workspaces - Choose data set.
% load('heatData_processed.mat')
load('coolData_processed.mat')
load('rawData.mat')


% adjust y axis for enthalpy not peak area --> divide by heating rate 
qdot = 10/60; % 10 degreesC/min in degC/s
Int_mean = Int_mean/qdot;
Int_std = Int_std/qdot;

%% Main result figure - Melting

Int_plus1S = Int_mean+Int_std;
Int_minus1S = Int_mean-Int_std;
Int_plus2S = Int_mean+2*Int_std;
Int_minus2S = Int_mean-2*Int_std;
v1 = [coord, coord; Int_mean, Int_plus1S].';
v2 = [coord, coord; Int_mean, Int_minus1S].';
v3 = [coord, coord; Int_plus1S, Int_plus2S].';
v4 = [coord, coord; Int_minus1S, Int_minus2S].';
f = [1 6 7 2; 2 7 8 3; 3 8 9 4; 4 9 10 5];

figure('Name','Result');
hold on
patch('Faces',f,'Vertices', v1,'FaceColor',[153/255 204/255 255/255],'EdgeColor','none','FaceAlpha', 1)
patch('Faces',f,'Vertices', v2,'FaceColor',[153/255 204/255 255/255],'EdgeColor','none','FaceAlpha', 1)
patch('Faces',f,'Vertices', v3,'FaceColor',[204/255 229/255 255/255],'EdgeColor','none','FaceAlpha', 1)
patch('Faces',f,'Vertices', v4,'FaceColor',[204/255 229/255 255/255],'EdgeColor','none','FaceAlpha', 1)
plot(coord, Int_mean, 'ko-','LineWidth',2)

h = zeros(3, 1);
h(1) = plot(NaN,NaN,'ko-', 'LineWidth', 1);
h(2) = plot(NaN,NaN,'Color',[153/255 204/255 255/255], 'LineWidth', 1);
h(3) = plot(NaN,NaN,'Color',[204/255 229/255 255/255], 'LineWidth', 1);
legend(h, {'Mean','1 SD', '2 SD'},...
    'Location', 'southwest',...
    'Orientation','horizontal',...
    'FontName','Helvetica',...
    'FontSize',12)

ax1 = gca; % Bottom horizontal axes
set(ax1,...
        'FontUnits','points',...
        'FontWeight','normal',...
        'FontSize',16,...
        'FontName','Helvetica',...
        'LineWidth',1.25,...
        'XTick',[1 2 3 4 5],... % Make custom labels
        'XtickLabel',{'Ctrl', '10^{8}','10^{9}','10^{10}','10^{11}'},...
        'XLim', [0.75, 5.25],...
        'XColor', 'k',...
        'YColor', 'k')
ylabel({'Melting enthalpy (J/g)'},...
        'FontUnits','points',...
        'FontSize',20,...
        'FontName','Helvetica')
xlabel({'4.5 MeV \alpha Fluence (ions/cm^2)'},...
        'FontUnits','points',...
        'FontSize',20,...
        'FontName','Helvetica')

% Second Axis
% For Nat., 5, 20, 90
enr = [0.72, 4.984, 20.14, 90.26]; %from my model
flu = [6.232e8 2.713e9 1.07e10 5.497e10]; %expected fluence
tic = log10(flu)-6;

ax2 = axes('Position',ax1.Position,...
    'XAxisLocation','top',...
    'YAxisLocation','right',...
    'Color','none');
set(ax2,...
        'FontUnits','points',...
        'FontWeight','normal',...
        'FontSize',16,...
        'FontName','Helvetica',...
        'LineWidth',1.25,...
        'XTick',tic,... % Make custom labels
        'XtickLabel',{'Nat.', '5%','20%','90%'},...
        'XLim', [0.75, 5.25],...
        'YTick', [],...
        'YTickLabel', [],...
        'XColor', 'k',...
        'YColor', 'k');
xlabel({'^{235}U enrichment for 1 year'},...
        'FontUnits','points',...
        'FontSize',20,...
        'FontName','Helvetica')
linkprop([ax1 ax2], {'Position', 'Units', 'ActivePositionProperty','PlotBoxAspectRatio'});
set(gca,'PlotBoxAspectRatio',[1 0.75 0.75])
set(gcf,'Position',[360 46 625 585]) %Make entire figure bigger

% title('Melting Enthalpy after Recrystallization at 10^{\circ}C/min')

%% Main result figure - Cooling

Int_plus1S = Int_mean+Int_std;
Int_minus1S = Int_mean-Int_std;
Int_plus2S = Int_mean+2*Int_std;
Int_minus2S = Int_mean-2*Int_std;
v1 = [coord, coord; Int_mean, Int_plus1S].';
v2 = [coord, coord; Int_mean, Int_minus1S].';
v3 = [coord, coord; Int_plus1S, Int_plus2S].';
v4 = [coord, coord; Int_minus1S, Int_minus2S].';
f = [1 6 7 2; 2 7 8 3; 3 8 9 4; 4 9 10 5];

figure('Name','Result');
hold on
patch('Faces',f,'Vertices', v1,'FaceColor',[153/255 204/255 255/255],'EdgeColor','none','FaceAlpha', 1)
patch('Faces',f,'Vertices', v2,'FaceColor',[153/255 204/255 255/255],'EdgeColor','none','FaceAlpha', 1)
patch('Faces',f,'Vertices', v3,'FaceColor',[204/255 229/255 255/255],'EdgeColor','none','FaceAlpha', 1)
patch('Faces',f,'Vertices', v4,'FaceColor',[204/255 229/255 255/255],'EdgeColor','none','FaceAlpha', 1)
plot(coord, Int_mean, 'ko-','LineWidth',2)

h = zeros(3, 1);
h(1) = plot(NaN,NaN,'ko-', 'LineWidth', 1);
h(2) = plot(NaN,NaN,'Color',[153/255 204/255 255/255], 'LineWidth', 1);
h(3) = plot(NaN,NaN,'Color',[204/255 229/255 255/255], 'LineWidth', 1);
legend(h, {'Mean','1 SD', '2 SD'},...
    'Location', 'southwest',...
    'Orientation','horizontal',...
    'FontName','Helvetica',...
    'FontSize',12)

ax1 = gca; % Bottom horizontal axes
set(ax1,...
        'FontUnits','points',...
        'FontWeight','normal',...
        'FontSize',16,...
        'FontName','Helvetica',...
        'LineWidth',1.25,...
        'XTick',[1 2 3 4 5],... % Make custom labels
        'XtickLabel',{'Ctrl', '10^{8}','10^{9}','10^{10}','10^{11}'},...
        'XLim', [0.75, 5.25],...
        'XColor', 'k',...
        'YColor', 'k')
ylabel({'Recrystallization enthalpy (J/g)'},...
        'FontUnits','points',...
        'FontSize',20,...
        'FontName','Helvetica')
xlabel({'4.5 MeV \alpha fluence (ions/cm^2)'},...
        'FontUnits','points',...
        'FontSize',20,...
        'FontName','Helvetica')

% Second Axis
% For Nat., 5, 20, 90
enr = [0.72, 4.984, 20.14, 90.26]; %from my model
flu = [6.232e8 2.713e9 1.07e10 5.497e10]; %expected fluence
tic = log10(flu)-6;

ax2 = axes('Position',ax1.Position,...
    'XAxisLocation','top',...
    'YAxisLocation','right',...
    'Color','none');
set(ax2,...
        'FontUnits','points',...
        'FontWeight','normal',...
        'FontSize',16,...
        'FontName','Helvetica',...
        'LineWidth',1.25,...
        'XTick',tic,... % Make custom labels
        'XtickLabel',{'Nat.', '5%','20%','90%'},...
        'XLim', [0.75, 5.25],...
        'YTick', [],...
        'YTickLabel', [],...
        'XColor', 'k',...
        'YColor', 'k');
xlabel({'^{235}U enrichment in 1 year'},...
        'FontUnits','points',...
        'FontSize',20,...
        'FontName','Helvetica')
linkprop([ax1 ax2], {'Position', 'Units', 'ActivePositionProperty','PlotBoxAspectRatio'});
set(gca,'PlotBoxAspectRatio',[1 0.75 0.75])
set(gcf,'Position',[360 46 625 585]) %Make entire figure bigger

%% Raw Data

figure;
hold on
plot(T_Cool_corr(:,57:68),Q_Cool_corr(:,57:68),'m','LineWidth',1)
plot(T_Cool_corr(:,45:56),Q_Cool_corr(:,45:56),'k','LineWidth',1)
plot(T_Cool_corr(:,33:44),Q_Cool_corr(:,33:44),'g','LineWidth',1)
plot(T_Cool_corr(:,21:32),Q_Cool_corr(:,21:32),'r','LineWidth',1)
plot(T_Cool_corr(:,1:20),Q_Cool_corr(:,1:20),'Color',[169/255 169/255 169/255],'LineWidth',1)
% 
% plot(T_Heat_corr(:,57:68),Q_Heat_corr(:,57:68),'m','LineWidth',1)
% plot(T_Heat_corr(:,45:56),Q_Heat_corr(:,45:56),'k','LineWidth',1)
% plot(T_Heat_corr(:,33:44),Q_Heat_corr(:,33:44),'g','LineWidth',1)
% plot(T_Heat_corr(:,21:32),Q_Heat_corr(:,21:32),'r','LineWidth',1)
% plot(T_Heat_corr(:,1:20),Q_Heat_corr(:,1:20),'Color',[169/255 169/255 169/255],'LineWidth',1)

h = zeros(5, 1);
h(1) = plot(NaN,NaN,'Color',[169/255 169/255 169/255], 'LineWidth', 2);
h(2) = plot(NaN,NaN,'r', 'LineWidth', 2);
h(3) = plot(NaN,NaN,'g', 'LineWidth', 2);
h(4) = plot(NaN,NaN,'k', 'LineWidth', 2);
h(5) = plot(NaN,NaN,'m', 'LineWidth', 2);
% legend(h, 'Unirradiated','10^{8} ions/cm^2','10^{9} ions/cm^2','10^{10} ions/cm^2','10^{11} ions/cm^2',...
%     'Location', 'south');
legend(h, 'Unirradiated','10^{8} ions/cm^2','10^{9} ions/cm^2','10^{10} ions/cm^2','10^{11} ions/cm^2',...
    'Location', 'south','Orientation', 'vertical');
set(gca,...
        'FontUnits','points',...
        'FontWeight','normal',...
        'FontSize',16,...
        'FontName','Helvetica',...
        'LineWidth',1.25,...
        'Box','on',...
        'XLim', [306 320.5],...
        'Ylim', [-0.1 1.35],...
        'XColor','k',...
        'YColor','k')
ylabel({'Heat flow (W/g), exo up'},...
        'FontUnits','points',...
        'FontSize',20,...
        'FontName','Helvetica')
xlabel({'Temperature (^{\circ}C)'},...
        'FontUnits','points',...
        'FontSize',20,...
        'FontName','Helvetica')

%% Flash DSC Figure

load('ProcessedForFigure.mat')

% Figure: over 2 - smoothed average/std by depth
figure;
hold on

% Plot mean with error shading (grey)
patch('Faces',f,'Vertices', v_2S,'FaceColor',[211/255 211/255 211/255],'EdgeColor','none','FaceAlpha', 0.3)
patch('Faces',f,'Vertices', v_1S,'FaceColor',[169/255 169/255 169/255],'EdgeColor','none','FaceAlpha', 0.3)
plot(x_mist-0.5,e_s2_avg,'k','LineWidth',2)

% Plot bars for expected values based on macroDSC
% patch('Faces',f_a,'Vertices', v_1,'FaceColor',[204/255 229/255 255/255],'EdgeColor','none','FaceAlpha', 0.5)
% patch('Faces',f_a,'Vertices', v_2,'FaceColor',[153/255 204/255 255/255],'EdgeColor','none','FaceAlpha', 0.5)
% patch('Faces',f_a,'Vertices', v_3,'FaceColor',[204/255 229/255 255/255],'EdgeColor','none','FaceAlpha', 0.5)
% patch('Faces',f_a,'Vertices', v_4,'FaceColor',[153/255 204/255 255/255],'EdgeColor','none','FaceAlpha', 0.5)
% plot([x_a x_b], [corr corr]-const, 'b-','LineWidth',1)
% plot([x_b x_c], [Int_mean(1) Int_mean(1)]-const, 'b-','LineWidth',1)

% Plot raw data
plot(x_oc(remOLs_oc),enth_oc(remOLs_oc),'bo')
plot(x_ocrc(remOLs_ocrc),enth_ocrc(remOLs_ocrc),'bo')
plot(x_nc(remOLs_nc),enth_nc(remOLs_nc),'bo')
plot(x_ncrc(remOLs_ncrc),enth_ncrc(remOLs_ncrc),'bo')
plot(x_43(remOLs_43),enth_43(remOLs_43),'bo')
plot(x_44(remOLs_44),enth_44(remOLs_44),'bo')
plot(x_c4x(remOLs_c4x),enth_c4x(remOLs_c4x),'go')
plot(x_74(remOLs_74),enth_74(remOLs_74),'go')
plot(x_75(remOLs_75),enth_75(remOLs_75),'go')
plot(x_76(remOLs_76),enth_76(remOLs_76),'go')
plot(x_77(remOLs_77),enth_77(remOLs_77),'go')
plot(x_c3x(remOLs_c3x),enth_c3x(remOLs_c3x),'ro')
plot(x_78(remOLs_78),enth_78(remOLs_78),'ro')
plot(x_79(remOLs_79),enth_79(remOLs_79),'ko')
plot(x_80(remOLs_80),enth_80(remOLs_80),'mo')

xlabel('Slice number ~ depth (\mum)')
ylabel('Recrystallization enthalpy (J/g)')
h = zeros(8, 1);
h(1) = plot(NaN,NaN,'bo');
h(2) = plot(NaN,NaN,'go');
h(3) = plot(NaN,NaN,'ro');
h(4) = plot(NaN,NaN,'ko');
h(5) = plot(NaN,NaN,'mo');
h(6) = plot(NaN,NaN,'k', 'LineWidth', 2);
h(7) = plot(NaN,NaN,'Color',[169/255 169/255 169/255], 'LineWidth', 1);
h(8) = plot(NaN,NaN,'Color',[211/255 211/255 211/255], 'LineWidth', 1);

legend(h, {'set 5','set 4','set 3','set 2', 'set 1','2\mum mean','1 SD','2 SD'},...
    'Location', 'eastoutside',...
    'Orientation','vertical',...
    'FontName','Helvetica',...
    'FontSize',12)

ax1 = gca; % Bottom horizontal axes
set(ax1,...
        'FontUnits','points',...
        'FontWeight','normal',...
        'FontSize',16,...
        'FontName','Helvetica',...
        'LineWidth',1.25,...
        'ylim',[2 42],...
        'xlim',[0 33],...
        'XColor', 'k',...
        'YColor', 'k',...
         'Box','on')
ylabel({'Recrystallization enthalpy (J/g)'},...
        'FontUnits','points',...
        'FontSize',20,...
        'FontName','Helvetica')
xlabel({'Slice number ~ depth (\mum)'},...
        'FontUnits','points',...
        'FontSize',20,...
        'FontName','Helvetica')

%% Flash DSC Figure - set 5 only

% Figure: over 2 - smoothed average/std by depth
figure;
hold on

% Plot mean with error shading (grey)
% patch('Faces',f,'Vertices', v_2S,'FaceColor',[211/255 211/255 211/255],'EdgeColor','none','FaceAlpha', 0.3)
% patch('Faces',f,'Vertices', v_1S,'FaceColor',[169/255 169/255 169/255],'EdgeColor','none','FaceAlpha', 0.3)
% plot(x_mist-0.5,e_s2_avg,'k','LineWidth',2)

% Plot bars for expected values based on macroDSC
% patch('Faces',f_a,'Vertices', v_1,'FaceColor',[204/255 229/255 255/255],'EdgeColor','none','FaceAlpha', 0.5)
% patch('Faces',f_a,'Vertices', v_2,'FaceColor',[153/255 204/255 255/255],'EdgeColor','none','FaceAlpha', 0.5)
% patch('Faces',f_a,'Vertices', v_3,'FaceColor',[204/255 229/255 255/255],'EdgeColor','none','FaceAlpha', 0.5)
% patch('Faces',f_a,'Vertices', v_4,'FaceColor',[153/255 204/255 255/255],'EdgeColor','none','FaceAlpha', 0.5)
% plot([x_a x_b], [corr corr]-const, 'b-','LineWidth',1)
% plot([x_b x_c], [Int_mean(1) Int_mean(1)]-const, 'b-','LineWidth',1)

% Plot raw data
plot(x_oc(remOLs_oc),enth_oc(remOLs_oc),'bo')
plot(x_ocrc(remOLs_ocrc),enth_ocrc(remOLs_ocrc),'go')
plot(x_nc(remOLs_nc),enth_nc(remOLs_nc),'ro')
plot(x_ncrc(remOLs_ncrc),enth_ncrc(remOLs_ncrc),'ko')
plot(x_43(remOLs_43),enth_43(remOLs_43),'mo')
plot(x_44(remOLs_44),enth_44(remOLs_44),'yo')
% plot(x_c4x(remOLs_c4x),enth_c4x(remOLs_c4x),'go')
% plot(x_74(remOLs_74),enth_74(remOLs_74),'go')
% plot(x_75(remOLs_75),enth_75(remOLs_75),'go')
% plot(x_76(remOLs_76),enth_76(remOLs_76),'go')
% plot(x_77(remOLs_77),enth_77(remOLs_77),'go')
% plot(x_c3x(remOLs_c3x),enth_c3x(remOLs_c3x),'ro')
% plot(x_78(remOLs_78),enth_78(remOLs_78),'ro')
% plot(x_79(remOLs_79),enth_79(remOLs_79),'ko')
% plot(x_80(remOLs_80),enth_80(remOLs_80),'mo')

xlabel('Slice Number ~ depth [\mum]')
ylabel('Recrystallizartion enthalpy [J/g]')
h = zeros(6, 1);
h(1) = plot(NaN,NaN,'bo');
h(2) = plot(NaN,NaN,'go');
h(3) = plot(NaN,NaN,'ro');
h(4) = plot(NaN,NaN,'ko');
h(5) = plot(NaN,NaN,'mo');
h(6) = plot(NaN,NaN,'yo');
% h(7) = plot(NaN,NaN,'Color',[169/255 169/255 169/255], 'LineWidth', 1);
% h(8) = plot(NaN,NaN,'Color',[211/255 211/255 211/255], 'LineWidth', 1);

legend(h, {'oc','ocrc','nc','ncrc','43','44'},...
    'Location', 'eastoutside',...
    'Orientation','vertical',...
    'FontName','Helvetica',...
    'FontSize',12)

ax1 = gca; % Bottom horizontal axes
set(ax1,...
        'FontUnits','points',...
        'FontWeight','normal',...
        'FontSize',16,...
        'FontName','Helvetica',...
        'LineWidth',1.25,...
        'ylim',[2 42],...
        'xlim',[0 33],...
        'XColor', 'k',...
        'YColor', 'k',...
         'Box','on')
ylabel({'Recrystallization enthalpy [J/g]'},...
        'FontUnits','points',...
        'FontSize',20,...
        'FontName','Helvetica')
xlabel({'Slice Number ~ depth [\mum]'},...
        'FontUnits','points',...
        'FontSize',20,...
        'FontName','Helvetica')

%% Flash DSC Figure - set 5 only, masses

% Figure: over 2 - smoothed average/std by depth
figure;
hold on

% Plot mean with error shading (grey)
% patch('Faces',f,'Vertices', v_2S,'FaceColor',[211/255 211/255 211/255],'EdgeColor','none','FaceAlpha', 0.3)
% patch('Faces',f,'Vertices', v_1S,'FaceColor',[169/255 169/255 169/255],'EdgeColor','none','FaceAlpha', 0.3)
% plot(x_mist-0.5,e_s2_avg,'k','LineWidth',2)

% Plot bars for expected values based on macroDSC
% patch('Faces',f_a,'Vertices', v_1,'FaceColor',[204/255 229/255 255/255],'EdgeColor','none','FaceAlpha', 0.5)
% patch('Faces',f_a,'Vertices', v_2,'FaceColor',[153/255 204/255 255/255],'EdgeColor','none','FaceAlpha', 0.5)
% patch('Faces',f_a,'Vertices', v_3,'FaceColor',[204/255 229/255 255/255],'EdgeColor','none','FaceAlpha', 0.5)
% patch('Faces',f_a,'Vertices', v_4,'FaceColor',[153/255 204/255 255/255],'EdgeColor','none','FaceAlpha', 0.5)
% plot([x_a x_b], [corr corr]-const, 'b-','LineWidth',1)
% plot([x_b x_c], [Int_mean(1) Int_mean(1)]-const, 'b-','LineWidth',1)

% Plot raw data
plot(x_oc(remOLs_oc),mass_oc(remOLs_oc),'b*')
plot(x_ocrc(remOLs_ocrc),mass_ocrc(remOLs_ocrc),'b*')
plot(x_nc(remOLs_nc),mass_nc(remOLs_nc),'b*')
plot(x_ncrc(remOLs_ncrc),mass_ncrc(remOLs_ncrc),'b*')
plot(x_43(remOLs_43),mass_43(remOLs_43),'b*')
plot(x_44(remOLs_44),mass_44(remOLs_44),'b*')
% plot(x_c4x(remOLs_c4x),enth_c4x(remOLs_c4x),'go')
% plot(x_74(remOLs_74),enth_74(remOLs_74),'go')
% plot(x_75(remOLs_75),enth_75(remOLs_75),'go')
% plot(x_76(remOLs_76),enth_76(remOLs_76),'go')
% plot(x_77(remOLs_77),enth_77(remOLs_77),'go')
% plot(x_c3x(remOLs_c3x),enth_c3x(remOLs_c3x),'ro')
% plot(x_78(remOLs_78),enth_78(remOLs_78),'ro')
% plot(x_79(remOLs_79),enth_79(remOLs_79),'ko')
% plot(x_80(remOLs_80),enth_80(remOLs_80),'mo')

xlabel('Slice Number ~ depth [\mum]')
ylabel('Mass, measured by C_p method [n/g]')
h = zeros(1, 1);
h(1) = plot(NaN,NaN,'bo');
% h(2) = plot(NaN,NaN,'go');
% h(3) = plot(NaN,NaN,'ro');
% h(4) = plot(NaN,NaN,'ko');
% h(5) = plot(NaN,NaN,'mo');
% h(6) = plot(NaN,NaN,'yo');
% h(7) = plot(NaN,NaN,'Color',[169/255 169/255 169/255], 'LineWidth', 1);
% h(8) = plot(NaN,NaN,'Color',[211/255 211/255 211/255], 'LineWidth', 1);
% 
% legend(h, {'oc','ocrc','nc','ncrc','43','44'},...
%     'Location', 'eastoutside',...
%     'Orientation','vertical',...
%     'FontName','Helvetica',...
%     'FontSize',12)

ax1 = gca; % Bottom horizontal axes
set(ax1,...
        'FontUnits','points',...
        'FontWeight','normal',...
        'FontSize',16,...
        'FontName','Helvetica',...
        'LineWidth',1.25,...
        'ylim',[90 270],...
        'xlim',[0 33],...
        'XColor', 'k',...
        'YColor', 'k',...
         'Box','on')
ylabel({'Mass by C_p method [n/g]'},...
        'FontUnits','points',...
        'FontSize',20,...
        'FontName','Helvetica')
xlabel({'Slice Number ~ depth [\mum]'},...
        'FontUnits','points',...
        'FontSize',20,...
        'FontName','Helvetica')

    
    