function [T,Q] = importDataCSV(filename)

%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Rachel\Documents\Rachel\MIT\MIT Research\Short Lab\n-Irradiated Al data May 2018\exported data csv\Control\al7075_ctrl_1_ramp2.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/06/03 10:19:29

%% Initialize variables.
delimiter = ',';
startRow = 4;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Time = dataArray{:, 1};
Temperature = dataArray{:, 2};
HeatFlowNormalized = dataArray{:, 3};
T = Temperature;
Q = HeatFlowNormalized;

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;

end